### PR TITLE
Added Grow Left, Right - Adjusts splitter up down

### PR DESCRIPTION
**Pull request by jglanz**
Super quick and dirty - but i hate taking my fingers off the keys - so it mostly works - Ctrl+E, -> or <- should move the appropriate spliters

### CODE REVIEW

**Comment by dkandalov** [comment]
Thank you!
Sounds like a really useful feature to me.
I'll try to look at the code later today.

**Comment by jglanz** [comment]
Def - the reality is the jetbrains sweet is the best ide hands down - but
the few aesthetic drawbacks just kill me - so i checked this one off - ill
add repeating key and tune it all when i get a few hrs

**Comment by dkandalov** [comment]
I finally got to play with the code and changed it a bit. Main changes:
 - different shortcuts (because cltr+e, -> is hard to press several times in a row)
 - renamed "grow" to "stretch" because there is similar action for toolwindows called "stretch"
 - separated left/right and up/down stretching
 - changed behaviour so that the first parent splitter is always used for stretching

I uploaded new jar to github. 
If you're happy with the changes, I'll release the plugin in the next couple days.

**Comment by jglanz** [comment]
All semantics - sounds good - i like ctrl e arrow was a copy from vim - but ive always been told im an odd duck - so i'll go with u ;)

Bueno - when i find sometime i'll run through the other items i mentioned
Jon



On Sun, Aug 21, 2016 at 10:31 AM -0400, "Dmitry Kandalov" <notifications@github.com> wrote:












I finally got to play with the code and changed it a bit. Main changes:


different shortcuts (because cltr+e, -> is hard to press several times in a row)
renamed "grow" to "stretch" because there is similar action for toolwindows called "stretch"
separated left/right and up/down stretching
changed behaviour so that the first parent splitter is always used for stretching




I uploaded new jar to github. 

If you're happy with the changes, I'll release the plugin in the next couple days.

**Pull request merged**
